import type { Metadata } from 'next'
import Head from 'next/head'

import { CssBaseline, ThemeProvider } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'

import theme from '@/styles/theme'

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'File Browser',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<Head>
				<link rel="shortcut icon" href="/favicon.ico" />
			</Head>
			<body>
				<AppRouterCacheProvider>
					<ThemeProvider theme={theme}>
						<CssBaseline />
						{children}
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	)
}
